version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: frasesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    build: ./backend
    environment:
      DB_HOST: db          # hostname interno
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: frasesdb
    ports:
      - "5000:5000"        # este puerto es el que expondrá ClawCloud Run
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
